import turtle as t
t.hideturtle()
t.setup(800,800)
t.screensize(900,900)
#-----------------------------------------A--------------------------
def A(x,y):
    t.pencolor('red')
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.write('A',move=False,align='center',font=('黑体',50,'normal'))

#-----------------------------------------框架------------------------
def frame():
    t.pencolor('black')
    t.penup()
    t.goto(250,0)
    t.pendown()
    t.setheading(90)
    t.forward(400)
    t.setheading(180)
    t.forward(500)
    t.setheading(-90)
    t.forward(800)
    t.setheading(0)
    t.forward(500)
    t.setheading(90)
    t.forward(400)
#-----------------------------------------爱心--------------------------
def heart1(a,i,j):
    t.penup()
    t.goto(i,j)
    t.pendown()
    t.begin_fill()
    t.color('red')
    t.setheading(115)
    t.circle(a,200)
    t.forward(2*a)
    t.left(90)
    t.forward(2*a)
    t.circle(a,200)
    t.end_fill()

def heart2(r,m,n):
    t.penup()
    t.goto(m,n)
    t.pendown()
    t.begin_fill()
    t.color('red')
    t.setheading(115)
    t.circle(-r,-200)
    t.forward(-2*r)
    t.left(-90)
    t.forward(2*r)
    t.circle(r,200)
    t.end_fill()
t.speed(0)  
A(-200,340)
frame()
heart1(10,-200,330)
heart2(40,0,0)
heart2(10,200,-330)
