import turtle as t
t.speed(0)
t.hideturtle()
def black1(a,i,j):#------正的黑桃
    t.penup()
    t.goto(i,j)
    t.pendown()
    t.begin_fill()
    t.color('black')
    t.setheading(115)
    t.circle(-a,-200)
    t.forward(-2*a)
    t.left(-90)
    t.forward(2*a)
    t.circle(a,200)
    t.setheading(180)
    t.forward(a/5)
    t.setheading(-90)
    t.forward(a/5)
    t.setheading(90)
    t.circle(a,-60)
    t.setheading(0)
    t.forward(a)
    t.setheading(152)
    t.circle(-a,60)
    t.end_fill()
def black2(r,m,n):#反
    t.penup()
    t.goto(m,n)
    t.pendown()
    t.begin_fill()
    t.color('black')
    t.setheading(115)
    t.circle(r,200)
    t.forward(2*r)
    t.left(90)
    t.forward(2*r)
    t.circle(r,200)
    t.setheading(0)
    t.forward(r/5)
    t.setheading(90)
    t.forward(r/5)
    t.setheading(90)
    t.circle(-r,60)
    t.setheading(180)
    t.forward(r)
    t.setheading(152)
    t.circle(r,-60)
    t.end_fill()


