import turtle as t
t.forward(70)
t.speed(0)
t.setheading(90)
t.color('red','red')
t.begin_fill()
t.circle(200,180)
t.end_fill()

t.color('orange','orange')
t.setheading(0)
t.forward(20)
t.setheading(-90)
t.begin_fill()
t.circle(180,-180)
t.end_fill()

t.color('yellow','yellow')
t.setheading(180)
t.penup()
t.forward(20)
t.pendown()
t.setheading(-90)
t.begin_fill()
t.circle(-160,-180)
t.end_fill()

t.color('green','green')
t.setheading(0)
t.forward(20)
t.penup()
t.setheading(-90)
t.pendown()
t.begin_fill()
t.circle(140,-180)
t.end_fill()

t.color('blue','blue')
t.setheading(180)
t.forward(20)
t.setheading(-90)
t.begin_fill()
t.circle(-120,-180)
t.end_fill()

t.color('indigo','indigo')
t.setheading(0)
t.forward(20)
t.setheading(-90)
t.begin_fill()
t.circle(100,-180)
t.end_fill()

t.color('purple','purple')
t.setheading(180)
t.forward(20)
t.setheading(-90)
t.begin_fill()
t.circle(-80,-180)
t.end_fill()

t.color('white','white')
t.setheading(0)
t.forward(20)
t.setheading(-90)
t.begin_fill()
t.circle(60,-180)
t.end_fill()
